
<!DOCTYPE html>
<html lang="pt_BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Projeto Político</title>

    <!-- Bootstrap core CSS -->
    <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/login.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

      <form class="form-horizontal" role="form" method="post">
			  <div class="form-group">
			    <label for="inputName" class="col-sm-2 control-label">Nome</label>
			    <div class="col-sm-5">
			      <input type="text" class="form-control" id="inputName" name="name" placeholder="seu nome" required>
			    </div>
			  </div>
			  <div class="form-group">
			    <label for="inputEmail3" class="col-sm-2 control-label">E-mail</label>
			    <div class="col-sm-5">
			      <input type="email" class="form-control" id="inputEmail3" name="email" placeholder="seu e-mail" required>
			    </div>
			  </div>
			  <div class="form-group">
			    <label for="inputState" class="col-sm-2 control-label">Estado</label>
			    <div class="col-sm-5">
			      <select class="form-control" name="state" id="inputState">
			      	<option value="0">-- selecione um estado --</option>
			      	<option value="1">Minas Gerais</option>
			      </select>
			    </div>
			  </div>
			  <div class="form-group">
			    <label for="inputPassword3" class="col-sm-2 control-label">Senha</label>
			    <div class="col-sm-5">
			      <input type="password" class="form-control" id="inputPassword3" name="password" placeholder="senha" required>
			    </div>
			  </div>
			  <div class="form-group">
			    <label for="inputPassword4" class="col-sm-2 control-label">Confirme sua senha</label>
			    <div class="col-sm-5">
			      <input type="password" class="form-control" id="inputPassword4" name="confirm_password" placeholder="confirme sua senha" required>
			    </div>
			  </div>
			  <div class="form-group">
			    <div class="col-sm-offset-2 col-sm-5">
			      <button type="submit" class="btn btn-default">Cadastrar</button>
			    </div>
			  </div>
			</form>

    </div> <!-- /container -->

  </body>
</html>
