
<!DOCTYPE html>
<html lang="pt_BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Acompanhe seu político</title>

    <!-- Bootstrap core CSS -->
    <link href="/libs/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/cover.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Acompanhe seu Político</h3>
              <ul class="nav masthead-nav">
                <li class="active"><a href="#">Home</a></li>
                <li><a href="#">Saiba Mais</a></li>
                <li><a href="#">Contato</a></li>
              </ul>
            </div>
          </div>

          <div class="inner cover">
            <h1 class="cover-heading">Acompanhe seu político.</h1>
            <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris accumsan sapien quis sem scelerisque, et pretium magna dignissim. Morbi nec placerat purus.</p>
            <p class="lead">
              <a href="/auth/login" class="btn btn-lg btn-default">Entrar</a>
            </p>
            Clique <a href="#">aqui</a> para cadastrar.
          </div>

          <div class="mastfoot">
            <div class="inner">
              <p>Todos direitos reservados, por <a href="https://twitter.com/andrehigher">@andrehigher</a>.</p>
            </div>
          </div>

        </div>

      </div>

    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/libs/jquery/jquery-1.11.0.min.js"></script>
    <script src="/libs/bootstrap/js/bootstrap.min.js"></script>
    <script src="/libs/docs.min.js"></script>
  </body>
</html>
